"""Add employee details

Revision ID: 24f0dcf53af9
Revises: 611e7adb60ea
Create Date: 2026-04-01 05:53:47.995829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '24f0dcf53af9'
down_revision: Union[str, None] = '611e7adb60ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('work_place', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('next_of_kin', sa.String(), nullable=True))
    op.add_column('users', sa.Column('next_of_kin_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employment_date', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employment_duration', sa.String(), nullable=True))
    op.add_column('users', sa.Column('national_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('has_computer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_computer')
    op.drop_column('users', 'national_id')
    op.drop_column('users', 'employment_duration')
    op.drop_column('users', 'employment_date')
    op.drop_column('users', 'next_of_kin_phone')
    op.drop_column('users', 'next_of_kin')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'work_place')
    # ### end Alembic commands ###
