"""add_notification_read_tracker

Revision ID: 48d6f711be8f
Revises: edae59b546f6
Create Date: 2026-03-25 06:56:46.017501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48d6f711be8f'
down_revision: Union[str, None] = 'edae59b546f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_reads_id'), 'notification_reads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_reads_id'), table_name='notification_reads')
    op.drop_table('notification_reads')
    # ### end Alembic commands ###
