"""remove employment_status enum

Revision ID: 512e89dc2a34
Revises: 24f0dcf53af9
Create Date: 2026-04-01 06:23:23.534987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '512e89dc2a34'
down_revision: Union[str, None] = '24f0dcf53af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # commands auto generated by Alembic - please adjust!
    op.execute("ALTER TABLE users ALTER COLUMN employment_status TYPE VARCHAR USING employment_status::text")
    op.execute("DROP TYPE IF EXISTS employmentstatusenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
