"""Add staff_no to user

Revision ID: 611e7adb60ea
Revises: f8459e608126
Create Date: 2026-03-31 13:22:33.159900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '611e7adb60ea'
down_revision: Union[str, None] = 'f8459e608126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_no', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['staff_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'staff_no')
    # ### end Alembic commands ###
