"""update_complaint_status

Revision ID: 86819daed103
Revises: 48d6f711be8f
Create Date: 2026-03-25 07:39:53.702396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86819daed103'
down_revision: Union[str, None] = '48d6f711be8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
