"""Add service_utilized

Revision ID: edae59b546f6
Revises: 74ea5dc12a73
Create Date: 2026-03-25 06:34:01.043202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'edae59b546f6'
down_revision: Union[str, None] = '74ea5dc12a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('service_utilized', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses', 'service_utilized')
    # ### end Alembic commands ###
