"""add is_hr to user

Revision ID: f8459e608126
Revises: aecc7d30a2ad
Create Date: 2026-03-31 11:44:18.018916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8459e608126'
down_revision: Union[str, None] = 'aecc7d30a2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_hr', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_hr')
    # ### end Alembic commands ###
